version: "3.9"

services:
  app:
    container_name: tmdb_app_ci
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    environment:
      GITHUB_ACTIONS: "true"   # Forces main.py â†’ run once
    volumes:
      - ./data:/app/data       # Make sure CSVs are saved in repo
    command: >
      sh -c "python -u src/main.py"


