version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: tmdb_app_ci
    env_file:
      - .env
    environment:
      GITHUB_ACTIONS: "true"
    command: >
      sh -c "python -u src/main.py"






